serializers and filters to set up api calls for Students(CourseMember)
Teamable-Analytics/teamable-backend pull request #17
Opened 2024-02-27 03:38 UTC by abeeto

- added/initialized filter directory: has a custom filter for CourseMember
- registered corresponding models to be able to add courseMember through admin page
- myUser  and section has serializers to retrieve attributes for Students table 

new files:
- app/serializers/myuser.py
- app/models/pagination.py

modified:
- accounts/models
- app/admin
- app/serializers/course.py
- app/serializers/course_member.py

2024-02-27 05:24 UTC, Opeyem1a commented
Note: Run `python3 -m black .` to fix the formatting project-wide (it will make the lint test pass)

2024-02-27 05:25 UTC, Opeyem1a commented on accounts/models.py
> +def __str__(self):
idk if this does what you think it does (?)

2024-02-27 05:26 UTC, Opeyem1a commented on app/admin.py
> +from accounts.models import MyUser
this one should go in its own admin.py in the `accounts` app (yes, the /app folder is a Django app called `app`, and `accounts` is another django app)

2024-02-28 16:18 UTC, Opeyem1a requested changes

2024-02-28 20:33 UTC, abeeto commented on app/models/pagination.py
> +    page_size = 2
It's the number of objects/rows returned for each table, I set to two just for testing.

2024-02-28 20:36 UTC, abeeto commented on app/models/pagination.py
Should I move it to app/views folder or to a new folder altogether.

2024-02-28 20:39 UTC, abeeto commented on app/serializers/myuser.py
> +        fields = ['id', 'username', 'first_name', 'last_name']
that makes sense, so I could make a CourseMember serializer that would just request for the id and name fields.

2024-02-28 21:05 UTC, abeeto commented on app/serializers/myuser.py
> +class SectionSerializer(serializers.ModelSerializer):
I think for purposes of student table, we'd only need the id, first name, and last name

2024-02-28 21:09 UTC, abeeto commented on app/serializers/course_member.py
> +
I don't know if this is the best way to do it but should we have this serializer for the purpose of the Student table, since I only need first and last name of user as well as the ID?

2024-02-29 04:05 UTC, Opeyem1a commented on app/models/pagination.py
new folder altogether

2024-02-29 04:05 UTC, Opeyem1a commented on app/serializers/course_member.py
> +
it's okay to send more data than you need, we can clean this up later

2024-02-29 04:07 UTC, Opeyem1a requested changes

2024-02-29 04:07 UTC, Opeyem1a commented on accounts/models.py
> +def __str__(self):
wait like remove this code though, I don't think it does anything

2024-02-29 04:07 UTC, Opeyem1a commented on app/serializers/myuser.py
> +class SectionSerializer(serializers.ModelSerializer):
why is the serializer for the Section model in the myuser.py file?

2024-02-29 04:07 UTC, Opeyem1a commented on app/serializers/myuser.py
> +class UserSerializer(serializers.ModelSerializer):
The MyUser model is a part of the `accounts` app, so it should be in that app's folder, you can just put it directly into `accounts/serializers.py` you don't need to make a folder

2024-03-01 01:18 UTC, abeeto commented on app/serializers/course.py
> +    def __str__(self):
I don't think we do. Deleted.

2024-03-01 01:19 UTC, abeeto commented on accounts/models.py
> +def __str__(self):
Yep, my bad, deleted.

2024-03-01 04:01 UTC, Opeyem1a requested changes

2024-03-01 04:01 UTC, Opeyem1a commented on accounts/myuser.py
Super nitpick, but this file should just be called `serializers.py`

Think of it like this, name the file what the things inside it are. When it's too much code for one file, name the folder what the things are and make subfiles within it

2024-03-01 04:04 UTC, abeeto commented on accounts/myuser.py
So do I move this into the existing serializers.py in the accounts folder?

2024-03-01 07:22 UTC, Opeyem1a approved these changes
Let's gooooo

2024-03-02 01:28 UTC, merged