Add model and API for students and sections
Teamable-Analytics/teamable-backend pull request #2
Opened 2024-02-13 02:29 UTC by justino599

Closes #1

2024-02-13 22:30 UTC, justino599 commented on app/models/section.py
> +    )
idk if you have an idea of how to use the name `course` instead of `course_fk`? I was getting an error about TimeStampedModel already having a column with the name `course`

2024-02-14 00:45 UTC, justino599 commented on app/models/section.py
> +    )
Another thing I just realized while manually testing the API, as this is, we have to use the key `course_fk` in the POST request for creating a new section. I don't know the severity of this problem if we're just gonna end up with utility functions that actually deal with this 🤷‍♂️ 

This issue also extends to a number of other tables that have a FK.

2024-02-14 16:43 UTC, Opeyem1a requested changes

2024-02-14 16:43 UTC, Opeyem1a commented on teamable/settings.py
> +        "ENGINE": "django.db.backends.postgresql",
the difference here was intentional, we actually don't need to dockerize the db at all and each person can just run a lightweight sqlite db for local dev, we can decide on the db for prod when we deploy

2024-02-14 16:43 UTC, Opeyem1a commented on app/serializers/course.py
>  class CourseSerializer(serializers.ModelSerializer):
not super necessary to split these into separate files yet but may as well I guess

2024-02-14 16:43 UTC, Opeyem1a commented on app/models/base_models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
To make it abstract you need:
```
class Meta:
        abstract = True
```

i.e. you dont actually want a "TimeStampedModel" table

I would also just call this `BaseModel` or consider doing some kind of model mixin type pattern (idk if this is possible, but think the same way django-rest does mixins for view classes)

2024-02-14 16:43 UTC, Opeyem1a commented on app/models/course.py
> +    OTHER = "O", _("Other")
No reason for this yet, would just have Canvas for now and make the field in the model be nullable

2024-02-14 16:43 UTC, Opeyem1a commented on app/models/section.py
> +    )
Yeah this would be annoying, try the abstract thing and if that doesnt work, look deeper into making models abstract in Django

2024-02-14 20:47 UTC, justino599 commented on teamable/settings.py
> +        "ENGINE": "django.db.backends.postgresql",
The reason I did this was because the migrations and the available model options differ depending on which db you have configured

2024-02-14 20:48 UTC, justino599 commented on app/models/base_models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
Ok, I'll look into that. I do remember seeing mixins being used in the django-rest tutorial

2024-02-15 19:38 UTC, justino599 commented on app/models/base_models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
Seems that mixins are just for Views, not models, and using abstract is proving the expected behavior.

2024-02-15 21:03 UTC, Opeyem1a approved these changes
just some questions

2024-02-15 21:03 UTC, Opeyem1a commented on app/urls.py
> +router.register("sections", SectionViewSet)
why did we remove students route? because it should be accessed through courses?

2024-02-15 21:03 UTC, Opeyem1a commented on teamable/settings.py
> +        "ENGINE": "django.db.backends.postgresql",
Fair enough, I'll resolve this with keyvan tonight - let's just push this through for now

don't have to do this now but these should come from .env fields (if you dont do now, make an issue)

2024-02-15 21:51 UTC, justino599 commented on app/urls.py
> +router.register("sections", SectionViewSet)
because there is no students model. There is only going to be `User` from auth, and `CourseMember`. I think GitHub is just displaying it weird, I originally just deleted all the existing models and rewrote everything

2024-02-15 21:58 UTC, merged