save attribute POST endpoint
Teamable-Analytics/teamable-backend pull request #27
Opened 2024-03-09 22:52 UTC by SanaBob

2024-03-24 03:18 UTC, Opeyem1a requested changes

2024-03-24 03:18 UTC, Opeyem1a commented on app/tests.py
> +if __name__ == "__main__":
why is this here?

2024-03-29 04:58 UTC, SanaBob commented on app/tests.py
> +if __name__ == "__main__":
I believe this is required to run unittest test suite

2024-04-02 04:35 UTC, Opeyem1a requested changes

2024-04-02 04:35 UTC, Opeyem1a commented on app/views/attribute.py
> +            AttributeOption.objects.filter(pk=attribute_option_id).update(
```suggestion
            attribute_option.update(
```

Don't you already have the object instance that you want to update?

2024-04-02 04:35 UTC, Opeyem1a commented on app/views/attribute.py
> +    def save_attribute(self, request):
this function likely needs to be in an atomic transaction - See `@transaction.atomic`

2024-04-02 04:42 UTC, SanaBob commented on app/views/attribute.py
> +            AttributeOption.objects.filter(pk=attribute_option_id).update(
https://stackoverflow.com/questions/67250135/why-is-it-not-possible-to-update-a-django-model-instance-like-this-instanceu
I believe there's no update function for django object instance unfortunately so we cannot do .update on attribute_option

2024-04-11 00:54 UTC, Opeyem1a approved these changes

2024-04-11 06:28 UTC, merged