adding first_name and last_name to accounts serializer
Teamable-Analytics/teamable-backend pull request #29
Opened 2024-03-11 15:09 UTC by abeeto

- added `first_name` and `last_name` to UserSerializer 
- removed previous  duplicate serializer I wrote.
- was unable to use `"__all__"` for the fields, I think it's because it's a `HyperlinedModelSerializer`

2024-03-14 06:33 UTC, Opeyem1a requested changes

2024-03-14 06:33 UTC, Opeyem1a commented on accounts/serializers.py
> -        model = MyUser
`MyUser` is the correct model to serialize. This is the one that we made and can edit. `User` comes from Django and we can't modify it in the future

2024-03-14 06:33 UTC, Opeyem1a commented on accounts/serializers.py
>  class UserSerializer(serializers.HyperlinkedModelSerializer):
What is the difference for hyperlinked model serializers? If we don't need the extra utility of it, we should just use model seralizer

Be careful though, if using `__all__` is exposing private user fields like password, then we should specify all of the fields we actually want manualyl

2024-03-17 16:09 UTC, abeeto commented on accounts/serializers.py
>  class UserSerializer(serializers.HyperlinkedModelSerializer):
Looks like hyperlinked model just represents the foreign and primary keys as the endpoints instead of the values. [Stackoverflow](https://stackoverflow.com/questions/33421147/what-is-the-benefit-of-using-a-hyperlinkedmodelserializer-in-drf)

Not sure which one would be better.

2024-03-17 16:24 UTC, abeeto commented on accounts/serializers.py
>  class UserSerializer(serializers.HyperlinkedModelSerializer):
![image](https://github.com/Teamable-Analytics/teamable-backend/assets/59943893/e6b552a5-8cc4-4fa3-aefb-d3bfea3fde18)

Yep, turns out specifying "__all__" does expose private fields like passwords. Going to specify the fields.

2024-03-18 08:17 UTC, Opeyem1a approved these changes

2024-03-18 15:16 UTC, merged