course_member: add course filter
Teamable-Analytics/teamable-backend pull request #30
Opened 2024-03-11 15:43 UTC by abeeto

- added a query param ('course'), so that I can pass in a course id into the endpoint to fetch relevant coursemembers 
- to be able to do task 2 of students spec.

2024-03-14 06:37 UTC, Opeyem1a requested changes

2024-03-14 06:37 UTC, Opeyem1a commented on app/filters/course_member.py
> +        course_param = request.query_params.get("course", None)
Django has a correct was to add filters to an endpoint. See https://www.django-rest-framework.org/api-guide/filtering/

Using query params is not necessarily wrong and the docs will discuss it as an option, but consider that essentially every request to this endpoint will need to at least filter by course. There is currently 0 use cases for ever calling it without filtering for a course.

Due to this, the request should probably be more like `.../course/1/students` and not `.../students?course=1` (do not take these url structures literally, this is just an illustrative example)

2024-03-17 19:09 UTC, abeeto commented on app/filters/course_member.py
> +        course_param = request.query_params.get("course", None)
In the front end, will the user be able to see the course/[course_id] part in the url.window? I remember something about how users shouldn't be able to switch between courses easily so I'm guessing that part won't be included in the url header.

2024-03-18 08:11 UTC, Opeyem1a commented on app/filters/course_member.py
> +        course_param = request.query_params.get("course", None)
This is something to be handled with validation once auth is implemented. We will know which user made the request on the server side and can grant or deny access based on that

2024-03-18 08:16 UTC, Opeyem1a approved these changes
Generally seems fine, pls get me that explainer video before merge though

2024-03-18 08:16 UTC, Opeyem1a commented on app/management/commands/makefakeclass.py
> +    @transaction.atomic
Nice

2024-03-18 08:16 UTC, Opeyem1a commented on app/views/course_member.py
> +    def by_course(self, request, course):
Maybe rename this to something more like `get_students_in_course`

I also fear I've made this task more difficult by asking for the changed url pattern, I think you did well, but can you record me something walking through this one @action endpoint and why you made the choices you made? Just haven't used it for this purpose before so wanna learn and confirm we're going down a good road

2024-03-24 16:31 UTC, merged