Nested team url
Teamable-Analytics/teamable-backend pull request #35
Opened 2024-03-24 01:11 UTC by ketphan02

Make the URLs of teams and team-templates to be nested with teamsets and teamset-templates respectively

This helps us filter the querysets to the correct teamset/teamset-template

2024-03-24 03:16 UTC, Opeyem1a requested changes

2024-03-24 03:16 UTC, Opeyem1a commented on app/views/teams.py
> +        return self.queryset.filter(team_set_id=self.kwargs["teamset_id"])
what if the key is not included in the kwargs?

2024-03-24 03:16 UTC, Opeyem1a commented on app/views/teams.py
> +        serializer.save(team_set_id=self.kwargs["teamset_id"])
what does this do? Like what if other info is being passed here? Why only create it with the teamset_id

2024-03-24 03:16 UTC, Opeyem1a commented on app/views/teams.py
> +    def get_queryset(self):
same comments for these 2 tbh

2024-03-24 09:29 UTC, ketphan02 commented on app/views/teams.py
> +        return self.queryset.filter(team_set_id=self.kwargs["teamset_id"])
If the url does not contains it, it will become 404 since no route is registered. if the teamset_id is wrong, it shows {"detail":"Not found."}

2024-03-24 09:30 UTC, ketphan02 commented on app/views/teams.py
> +        serializer.save(team_set_id=self.kwargs["teamset_id"])
Actually was copying code, should not add when not needed

2024-03-25 15:56 UTC, Opeyem1a commented on app/urls.py
Actually wait now I'm thinking about it, why are we doing things related to team and teamset in this PR? Isn't it for the projects page?

2024-03-25 15:58 UTC, Opeyem1a commented on app/views/teams.py
> +        return self.queryset.filter(team_set_id=self.kwargs["teamset_id"])
even though it shouldn't be an invalid key, I don't like the way it does this, much prefer the use of `.get_object_or_404()` with a 404 thrown if it's not a valid teamset id

Like first we use `.get()` with a default of None, then we try to fetch that teamset by id, then filter queryset after

2024-03-25 15:58 UTC, Opeyem1a commented on app/views/teams.py
> +        return self.queryset.filter(team_set_id=self.kwargs["teamset_id"])
This applies to both

2024-05-10 08:20 UTC, Opeyem1a requested changes

2024-05-10 08:20 UTC, Opeyem1a commented on app/views/teams.py
> +        return get_object_or_404(self.queryset, pk=self.kwargs["teamset_id"])
wait isn't this the wrong query?

You want to filter for Teams where Team.teamset_id=teamset_id

Not pk=teamset_id

(I'm making up field names since I forgot the exact name of the FK)

2024-05-10 08:20 UTC, Opeyem1a commented on app/views/teams.py
> +        return get_object_or_404(self.queryset, pk=self.kwargs["teamset_template_id"])
same query problem here

2024-05-10 09:47 UTC, Opeyem1a requested changes

2024-05-10 09:47 UTC, Opeyem1a commented on app/views/teams.py
> +        teamset = self.queryset.filter(teamset=self.kwargs["teamset_id"])
wait can't you still use get_object_or_404?

just like `get_object_or_404(teamset=self.kwargs["teamset_id"])` or something (test it)

2024-05-11 02:48 UTC, ketphan02 commented
@Opeyem1a I think the real issue is it doesn't exist in the queryset. We need to check if the id exists in the higher level object first

2024-09-08 09:39 UTC, closed without merging