Course members filter sections
Teamable-Analytics/teamable-backend pull request #39
Opened 2024-03-25 21:30 UTC by abeeto

extension of #37:
- changes made so that it's possible to filter coursemembers (students) such that it returns objects with that section.
- intended use:
   - If  there are 3 sections: 1, 2, 3.  Selecting sections [1,2]  will return all students with 1 OR 2. So students with section [1,3] or [2,3] will still be returned.
   - It's chaining the sections conditions using OR operator not AND operator.

2024-03-27 17:44 UTC, Opeyem1a requested changes

2024-03-27 17:44 UTC, Opeyem1a commented on app/filters/course_member.py
> +        sections = sections.split(".") if sections else None
why are the sections separated by a period and not a comma?

2024-03-27 17:44 UTC, Opeyem1a commented on app/filters/course_member.py
> +                query |= Q(sections=section)
you don't have to for loop this, you can clean this up since Django has syntax that looks kinda like `Q(sections__in=sections)` (look into the docs for this)

2024-03-28 13:15 UTC, abeeto commented on app/filters/course_member.py
> +        sections = sections.split(".") if sections else None
No real reason other than that I based it off:
![image](https://github.com/Teamable-Analytics/teamable-backend/assets/59943893/b61ba1de-6846-4a47-8c29-be120749aeba)

I'm good with using commas if that's the norm/convention.

2024-03-28 13:31 UTC, abeeto commented on app/filters/course_member.py
> +                query |= Q(sections=section)
that's clean! the field lookup seems super powerful but in general I'm slightly confused on when I can just __ things.

2024-03-29 04:16 UTC, Opeyem1a commented on app/filters/course_member.py
> +        sections = sections.split(".") if sections else None
generally, yes

2024-03-29 04:16 UTC, Opeyem1a commented on app/filters/course_member.py
> +                query |= Q(sections=section)
docs on this are sometimes a bit deep, but yeah they have __in, __not_in and some others

2024-03-29 04:36 UTC, Opeyem1a approved these changes

2024-03-29 04:40 UTC, merged