added fetch by id for course
Teamable-Analytics/teamable-backend pull request #42
Opened 2024-04-27 04:12 UTC by SanaBob

2024-04-28 23:01 UTC, Opeyem1a requested changes

2024-04-28 23:01 UTC, Opeyem1a commented on app/views/course.py
> +        course_id = self.request.query_params.get("id", None)
idk how much I like this, it basically means if we ever filter by course is will use the limited version of the serializer.

Why did we need the 2nd serializer in the first place btw? If the extra data returned in a course is not significant, we could have just used the existing one

2024-04-28 23:01 UTC, Opeyem1a commented on app/views/course.py
> +    def get_queryset(self):
why did we need to define this function? Would it have already 404'd without it?

2024-04-28 23:09 UTC, SanaBob commented on app/views/course.py
> +    def get_queryset(self):
It returns an empty list when there is no match

2024-04-28 23:11 UTC, SanaBob commented on app/views/course.py
> +        course_id = self.request.query_params.get("id", None)
We can just use the 1st serializer, but I thought the spec only wanted limited data on specific search param courseId only, and this happen to be the only way I found possible

2024-04-29 03:24 UTC, SanaBob commented
I didn't know that search by parameter was in default view, but I have verified that it works

2024-04-29 13:03 UTC, Opeyem1a requested changes

2024-04-29 13:03 UTC, Opeyem1a commented on app/serializers/course.py
> -    attributes = AttributeSerializer(many=True, read_only=True)
I think you misunderstood my comment. I was just challenging that if the difference between your new serializer and the old one is trivial, don't make a new one. In this case, this is not really trivial to just delete this part from the serializer

2024-05-01 05:11 UTC, closed without merging