Add Enrollment and Relationship models
Teamable-Analytics/teamable-backend pull request #7
Opened 2024-02-13 23:48 UTC by justino599

Closes #3

2024-02-13 23:50 UTC, justino599 commented on app/models/enrollment.py
> +    """
Should we keep this as `Enrollment`? Or should we user something more like `EnrolledUser`

2024-02-15 06:25 UTC, Opeyem1a requested changes

2024-02-15 06:25 UTC, Opeyem1a commented on app/models/enrollment.py
> +    TA = "T", _("TA")
wouldn't add this for now

2024-02-15 06:25 UTC, Opeyem1a commented on app/models/enrollment.py
> +    """
Maybe like CourseMember

I like this because we can make FKs that go here be like `from_member` instead of `from_user`, which implies the User model

2024-02-15 06:25 UTC, Opeyem1a commented on app/models/relationship.py
> +    to_user = models.ForeignKey(Enrollment, on_delete=models.CASCADE)
nit;

maybe a related_name of "inbound_relationships" or something

then perhaps change the first one to "outbound relationships"

2024-02-15 21:07 UTC, Opeyem1a approved these changes
nits only

2024-02-15 21:07 UTC, Opeyem1a commented on app/models/course_member.py
> +    Models a user's involvement in a section (or group).
nit;

seems kinda incorrect, I would personally just yeet this whole comment

2024-02-15 21:07 UTC, Opeyem1a commented on app/models/course_member.py
> +    lms_id = models.CharField(max_length=100, blank=True)
nit;

maybe overkill but perhaps something like `external_lms_id`

2024-02-15 21:56 UTC, justino599 commented on app/models/course_member.py
> +    lms_id = models.CharField(max_length=100, blank=True)
makes it clearer, I like it

2024-02-15 21:58 UTC, merged