Added missing info to the project installation guide in README
Teamable-Analytics/teamable-backend pull request #70
Opened 2024-10-08 19:13 UTC by colton456p

I added the missing database migrations line to the project installation guide along with a few other lines I thought might be useful for someone running the backend code for the first time. If you think these extra lines are redundant please let me know and I will keep the README the same as it was before + database migrations line.

2024-10-09 03:01 UTC, Opeyem1a requested changes

2024-10-09 03:01 UTC, Opeyem1a commented on README.md
> +   python3 -m venv venv
wait do we need the `venv venv`? Or just a typo?

2024-10-09 17:11 UTC, colton456p commented on README.md
> +   python3 -m venv venv
Yea it is needed, `-m venv` tells Python to run the venv module and creates the virtual environment and the second `venv` is the name of the directory that will be created to hold the virtual environment files. The second venv is interchangeable and could be named whatever you want your virtual environment folder to be named but I called it `venv` because "venv/" was in the gitignore folder which suggests that the virtual environment folder must be called "venv" in order to not be pushed to GH.

2024-10-12 01:31 UTC, Opeyem1a commented on README.md
> +   python3 -m venv venv
Okay fair enough

2024-10-12 01:31 UTC, Opeyem1a approved these changes

2024-10-15 18:46 UTC, merged