Add projects and project sets
Teamable-Analytics/teamable-backend pull request #8
Opened 2024-02-14 00:39 UTC by justino599

Closes #5

2024-02-15 06:27 UTC, Opeyem1a requested changes

2024-02-15 06:27 UTC, Opeyem1a commented on app/models/projects.py
> +    project_set_fk = models.ForeignKey(
all things with `_fk` shouldn't need to have the fk, but we'll solve that on the base branch

2024-02-15 21:08 UTC, Opeyem1a requested changes

2024-02-15 21:08 UTC, Opeyem1a commented on app/models/projects.py
> +    project = models.ForeignKey(
```suggestion
    project_set = models.ForeignKey(
```

2024-02-15 21:53 UTC, justino599 commented on app/models/projects.py
> +    project = models.ForeignKey(
Good catch

2024-02-24 23:49 UTC, Opeyem1a commented
Also deprecated by https://github.com/Teamable-Analytics/teamable-backend/pull/14

2024-02-26 20:24 UTC, closed without merging